gpu: msm: kgsl: remove unused variable
../drivers/gpu/msm/kgsl.c:4969:6: error: unused variable 'cpu' [-Werror,-Wunused-variable]
        int cpu;
            ^
1 error generated.